- ubuntu-precise
(idea by @timfel, see https://github.com/dex4er/fakechroot)
> Add ability to use a bootstrapped chroot w/o sudo

- ubuntu-precise
adds libreadline-gplv2-dev, automake1.9, dpatch, hardening-wrapper, libaio-dev
> packages for mariadb-10 libreadline-gplv2-dev, automake1.9, dpatch, hardening-wrapper, libaio-dev

- ubuntu-precise
For travis-ci/travis-ci#4322.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944248
> Pull request for libexplain-dev

- ubuntu-precise
For travis-ci/travis-ci#4340.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71959103
> Pull request for tomcat7

- ubuntu-precise
For travis-ci/travis-ci#4336.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71959057
> Pull request for srecord

- ubuntu-precise
For travis-ci/travis-ci#4331.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71958969
> Pull request for python-markdown

- ubuntu-precise
For travis-ci/travis-ci#4360.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71961716
> Pull request for libace-dev

- ubuntu-precise
For travis-ci/travis-ci#4361.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71961718
> Pull request for rrdtool

- ubuntu-precise
For travis-ci/travis-ci#4371.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71975786
> Pull request for libfann-dev

- ubuntu-precise
For travis-ci/travis-ci#4428.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71986651
> Pull request for libcln-dev

- ubuntu-precise
For travis-ci/travis-ci#4448.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71998798
> Pull request for python-samba

- ubuntu-precise
For travis-ci/travis-ci#3741.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72046037
> Pull request for libgdal-dev

- ubuntu-precise
Reverts travis-ci/apt-package-whitelist#31
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72216065
> Revert "Pull request for libcap-ng-dev"

- ubuntu-precise
For travis-ci/travis-ci#4297.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72141514
> Pull request for libsmi2-dev

- ubuntu-precise
For travis-ci/travis-ci#4453.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206918
> Pull request for pyside-tools

- ubuntu-precise
For travis-ci/travis-ci#4493.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206928
> Pull request for libglui-dev

- ubuntu-precise
For travis-ci/travis-ci#4496.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206936
> Pull request for libx264-dev

- ubuntu-precise
For travis-ci/travis-ci#4344.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206971
> Pull request for libsmi2ldbl

- ubuntu-precise
For travis-ci/travis-ci#4497.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206980
> Pull request for libopenimageio-dev

- ubuntu-precise
For travis-ci/travis-ci#4454.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207157
> Pull request for libopencascade-dev

- ubuntu-precise
For travis-ci/travis-ci#4427.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72208033
> Pull request for gmsh

- ubuntu-precise
For travis-ci/travis-ci#4484. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72225904
> Pull request for libgconf2-dev

- ubuntu-precise
For travis-ci/travis-ci#4504. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72228997
> Pull request for fonts-texgyre

- ubuntu-precise
For travis-ci/travis-ci#4522. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229086
> Pull request for libsword-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#194. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229268
> Pull request for thrift-compiler

- ubuntu-precise
For travis-ci/apt-package-whitelist#207. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229325
> Pull request for libmuparser-dev

- ubuntu-precise
For travis-ci/travis-ci#4471.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207478
> Pull request for libnl-3-dev

- ubuntu-precise
For travis-ci/travis-ci#4461.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206922
> Pull request for libcoin60-doc

- ubuntu-precise
For travis-ci/apt-package-whitelist#40. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284613
> Pull request for flexc++

- ubuntu-precise
Resolves https://github.com/travis-ci/travis-ci/issues/4507
> Add lam-mpidoc lam4-dev liblam4 lam-runtime

- ubuntu-precise
For travis-ci/apt-package-whitelist#328. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365343
> Pull request for libesd0-dev

- ubuntu-precise
For travis-ci/travis-ci#4508. adding packages: highlight
> Pull request for highlight

- ubuntu-precise
For travis-ci/apt-package-whitelist#105. adding packages: augeas-tools libaugeas-dev libaugeas0 augeas-dbg augeas-lenses augeas-doc
> Pull request for augeas-tools

- ubuntu-precise
For travis-ci/travis-ci#4550. adding packages: latex2html
> Pull request for latex2html

- ubuntu-precise
Add packages: python-pygments python3-pygments python-pygments-doc
> Pull request for python-pygments; Resolves travis-ci/apt-package-whitelist#175.

- ubuntu-precise
> Pull request for php5-gnupg; Resolves travis-ci/travis-ci#4062.

- ubuntu-precise
> Pull request for percona-toolkit; Resolves travis-ci/apt-package-whitelist#348.

- ubuntu-precise
Add packages: liblcms1 liblcms-utils liblcms1-dev python-liblcms
> Pull request for liblcms1; Resolves travis-ci/apt-package-whitelist#349.

- ubuntu-precise
Add packages: libsecret-1-dev libsecret-1-0 libsecret-common libsecret-tools gir1.2-secret-1
> Pull request for libsecret-1-dev; Resolves travis-ci/apt-package-whitelist#350.

- ubuntu-precise
For travis-ci/apt-package-whitelist#199. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229308
> Pull request for python-protobuf

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#355.
Add packages: libnspr4 libnspr4-0d libnspr4-dev libnspr4-dbg
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545277.
> Pull request for libnspr4

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#374.
Add packages: python-swiftclient
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545387
> Pull request for python-swiftclient

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#376.
Add packages: shellcheck
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545399
> Pull request for shellcheck

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#389.
Add packages: python-pycountry python3-pycountry
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545466
> Pull request for python-pycountry

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#395.
Add packages: python3 python3-venv python3-minimal python3-examples python3-dev libpython3-dev libpython3-stdlib idle3 python3-doc python3-dbg libpython3-dbg python3-all python3-all-dev python3-all-dbg libpython3-all-dev libpython3-all-dbg
See https://github.com/travis-ci/apt-package-whitelist/issues/395
> Pull request for python3

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#398.
Add packages: python-nose-doc python-nose python3-nose
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545517
> Pull request for python-nose-doc

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#401.
Add packages: python-pandas python3-pandas python-pandas-doc python-pandas-lib python3-pandas-lib
https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545541
> Pull request for python-pandas

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#421.
Add packages: python-requests python3-requests python-requests-whl
See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545615.
> Pull request for python-requests

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#440.
Add packages: tesseract-ocr-dev libtesseract-dev libtesseract3 tesseract-ocr tesseract-ocr-all
See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545679.
> Pull request for tesseract-ocr-dev

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#445.
Add packages: fontforge fontforge-nox fontforge-common libfontforge-dev libfontforge1 libgdraw4 python-fontforge fontforge-dbg
See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545693.
> Pull request for fontforge

- make_pr.sh
Just a minor linguistic fix to the automated issue/PR response.
> Fix sentence structure in automated PR comment

- ubuntu-trusty
Reverts travis-ci/apt-package-whitelist#3851
Didn't find the source. Ooops.
> Revert "Pull request for srecord in trusty"

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/travis-ci/apt-package-whitelist/3902)
> Fix Precse to be Precise
