travis-ci/apt-package-whitelist

- ubuntu-precise
Some dependencies are already whitelisted, here's the full list:
```
The following NEW packages will be installed:
antlr checkstyle java-wrappers libantlr-java libapache-pom-java
libcommons-beanutils-java libcommons-cli-java libcommons-lang-java
libcommons-logging-java libcommons-parent-java libgoogle-collections-java
libjsr305-java
```
> APT whitelist request for checkstyle + dependencies

- ubuntu-precise
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71904879
> Pull request for postgis

- ubuntu-precise
For travis-ci/travis-ci#4278.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71933272
> Pull request for intltool

- ubuntu-precise
For travis-ci/travis-ci#4280.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71933832
> Pull request for rst2pdf

- ubuntu-precise
For travis-ci/travis-ci#4287.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71933881
> Pull request for jansson

- ubuntu-precise
For travis-ci/travis-ci#4286.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71933864
> Pull request for discount

- ubuntu-precise
For travis-ci/travis-ci#4288.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71933993
> Pull request for haskell-platform

- ubuntu-precise
For travis-ci/travis-ci#4289.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71934224
> Pull request for equivs

- ubuntu-precise
For travis-ci/travis-ci#4297.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71937073
> Pull request for libsmi2-dev

- ubuntu-precise
For travis-ci/travis-ci#4308.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71937210
> Pull request for libxerces-c-dev

- ubuntu-precise
For travis-ci/travis-ci#4298.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71937155
> Pull request for libcap-ng-dev

- ubuntu-precise
For travis-ci/travis-ci#4302.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71937199
> Pull request for libprotoc-dev

- ubuntu-precise
For travis-ci/travis-ci#4300.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71937193
> Pull request for libarmadillo-dev

- ubuntu-precise
For travis-ci/travis-ci#4310.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71937263
> Pull request for gcc-arm-none-eabi

- ubuntu-precise
For travis-ci/travis-ci#4325.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944358
> Pull request for libopenjpeg-dev

- ubuntu-precise
For travis-ci/travis-ci#4315.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944218
> Pull request for libsvm-dev

- ubuntu-precise
For travis-ci/travis-ci#4321.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944237
> Pull request for cppcheck

- ubuntu-precise
For travis-ci/travis-ci#4328.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71944413
> Pull request for markdown

- ubuntu-precise
For travis-ci/travis-ci#4329.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71947015
> Pull request for libconfig-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#42.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71957555
> Pull request for hunspell

- ubuntu-precise
For travis-ci/travis-ci#4333.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71958980
> Pull request for libpolarssl-dev

- ubuntu-precise
For travis-ci/travis-ci#4334.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71958990
> Pull request for electric-fence

- ubuntu-precise
For travis-ci/travis-ci#4330.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71958950
> Pull request for libxml-xpath-perl

- ubuntu-precise
For travis-ci/travis-ci#4342.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71959115
> Pull request for biblatex

- ubuntu-precise
For travis-ci/travis-ci#4343.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71961707
> Pull request for chktex

- ubuntu-precise
For travis-ci/travis-ci#4338.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71959082
> Pull request for tcpdump

- ubuntu-precise
For travis-ci/travis-ci#4332.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71958975
> Pull request for python-pywbem

- ubuntu-precise
For travis-ci/travis-ci#4363.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71969747
> Pull request for libsdl1.2-dev:i386

- ubuntu-precise
For travis-ci/travis-ci#4367.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71969792
> Pull request for xsdcxx

- ubuntu-precise
For travis-ci/travis-ci#4365.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71969772
> Pull request for libpstreams-dev

- ubuntu-precise
For travis-ci/travis-ci#4366.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71969774
> Pull request for libxerces-c2-dev

- ubuntu-precise
For travis-ci/travis-ci#4364.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71969765
> Pull request for libgraphicsmagick++1-dev

- ubuntu-precise
For travis-ci/travis-ci#4375.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71975809
> Pull request for libiptcdata

- ubuntu-precise
For travis-ci/travis-ci#4381.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71982134
> Pull request for libaa1

- ubuntu-precise
For travis-ci/travis-ci#4385.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71982995
> Pull request for moreutils

- ubuntu-precise
For travis-ci/travis-ci#4382.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71982974
> Pull request for elinks

- ubuntu-precise
For travis-ci/travis-ci#4425.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71983062
> Pull request for libghc-gstreamer-dev

- ubuntu-precise
For travis-ci/travis-ci#4386.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71983034
> Pull request for bash-completion

- ubuntu-precise
For travis-ci/travis-ci#4434.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71987222
> Pull request for socklog

- ubuntu-precise
For travis-ci/travis-ci#4431.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71987186
> Pull request for libarpack2-dev

- ubuntu-precise
For travis-ci/travis-ci#4433.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71987207
> Pull request for runit

- ubuntu-precise
For travis-ci/travis-ci#4430.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71987167
> Pull request for libmumps-dev

- ubuntu-precise
For travis-ci/travis-ci#4432.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71987196
> Pull request for libhypre-dev

- ubuntu-precise
For travis-ci/travis-ci#4429.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71987162
> Pull request for transfig

- ubuntu-precise
For travis-ci/travis-ci#4439.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71992274
> Pull request for dh-autoreconf

- ubuntu-precise
For travis-ci/travis-ci#4436.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71992257
> Pull request for proxychains

- ubuntu-precise
For travis-ci/travis-ci#4441.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71995942
> Pull request for libcoq-ocaml-dev

- ubuntu-precise
For travis-ci/travis-ci#4440.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71992302
> Pull request for coq

- ubuntu-precise
For travis-ci/travis-ci#4442.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71996356
> Pull request for python-pexpect

- ubuntu-precise
For travis-ci/travis-ci#4445.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71998735
> Pull request for libocamlgraph-ocaml-dev

- ubuntu-precise
For travis-ci/travis-ci#4444.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71998731
> Pull request for libgraphviz4

- ubuntu-precise
For travis-ci/travis-ci#4443.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71997291
> Pull request for camlp5

- ubuntu-precise
For travis-ci/travis-ci#4446.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71998743
> Pull request for liblablgtk2-ocaml-dev

- ubuntu-precise
For travis-ci/travis-ci#4447.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/71998768
> Pull request for liblablgtksourceview2-ocaml-dev

- ubuntu-precise
For travis-ci/travis-ci#4226.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72046060
> Pull request for cython

- ubuntu-precise
For travis-ci/travis-ci#4351.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72204830
> Pull request for sox

- ubuntu-precise
For travis-ci/travis-ci#4379.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72204844
> Pull request for pwgen

- ubuntu-precise
For travis-ci/travis-ci#4401.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72204848
> Pull request for python-pygresql

- ubuntu-precise
For travis-ci/travis-ci#4242.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206840
> Pull request for python-jinja2

- ubuntu-precise
For travis-ci/travis-ci#4243.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206834
> Pull request for python-markupsafe

- ubuntu-precise
For travis-ci/travis-ci/travis-ci#4314.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206854
> Pull request for python-numexpr

- ubuntu-precise
For travis-ci/travis-ci#4239.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206869
> Pull request for python-cheetah

- ubuntu-precise
For travis-ci/travis-ci#4494.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206930
> Pull request for libtinyxml-dev

- ubuntu-precise
For travis-ci/travis-ci#4465.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206920
> Pull request for iptables-dev

- ubuntu-precise
For travis-ci/travis-ci#4485.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206924
> Pull request for libnss3-dev

- ubuntu-precise
For travis-ci/travis-ci#4492.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206926
> Pull request for libcaca-dev

- ubuntu-precise
For travis-ci/travis-ci#4462.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206948
> Pull request for libspnav-dev

- ubuntu-precise
For travis-ci/travis-ci/travis-ci#4457.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206975
> Pull request for libzipios++-dev

- ubuntu-precise
For travis-ci/travis-ci#4456.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206989
> Pull request for libode-dev

- ubuntu-precise
For travis-ci/travis-ci#4345.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72206967
> Pull request for snmp-mibs-downloader

- ubuntu-precise
For travis-ci/travis-ci#4455.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207102
> Pull request for libshiboken-dev

- ubuntu-precise
For travis-ci/travis-ci#4402.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207089
> Pull request for libhdf4-dev

- ubuntu-precise
For travis-ci/travis-ci#4419.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207121
> Pull request for ocaml-findlib

- ubuntu-precise
For travis-ci/travis-ci#4407.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207164
> Pull request for libqrencode3

- ubuntu-precise
For travis-ci/travis-ci#4467.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207203
> Pull request for libdbus-glib-1-dev

- ubuntu-precise
For travis-ci/travis-ci#4405.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207184
> Pull request for libcfitsio3-dev

- ubuntu-precise
For travis-ci/travis-ci#4404.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207192
> Pull request for libhdfeos-dev

- ubuntu-precise
For travis-ci/travis-ci#4450.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207250
> Pull request for libsoqt4-dev

- ubuntu-precise
For travis-ci/travis-ci#4412.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207272
> Pull request for doxygen-latex

- ubuntu-precise
For travis-ci/travis-ci#4356.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207388
> Pull request for xdot

- ubuntu-precise
For travis-ci/travis-ci#4418.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207340
> Pull request for noweb

- ubuntu-precise
For travis-ci/travis-ci#4466.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207452
> Pull request for libnfnetlink-dev

- ubuntu-precise
For travis-ci/travis-ci#4469.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207521
> Pull request for gstreamer0.10-plugins-base

- ubuntu-precise
For travis-ci/travis-ci#4495.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207557
> Pull request for yasm

- ubuntu-precise
For travis-ci/travis-ci#4491.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207541
> Pull request for libraw-dev

- ubuntu-precise
For travis-ci/travis-ci#4468. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72223895
> Pull request for libgstreamer-plugins-base0.10-dev

- ubuntu-precise
For travis-ci/travis-ci#4486. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72226181
> Pull request for octave

- ubuntu-precise
For travis-ci/travis-ci#4506. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229006
> Pull request for nsis-common

- ubuntu-precise
For travis-ci/travis-ci#4510. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229030
> Pull request for asymptote

- ubuntu-precise
For travis-ci/travis-ci#4509. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229026
> Pull request for coffeescript

- ubuntu-precise
For travis-ci/travis-ci#4511. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229051
> Pull request for scala

- ubuntu-precise
For travis-ci/travis-ci#4538. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229109
> Pull request for libxvidcore4

- ubuntu-precise
For travis-ci/apt-package-whitelist#192. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229245
> Pull request for bzr-fastimport

- ubuntu-precise
For travis-ci/apt-package-whitelist#193. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229258
> Pull request for psutils

- ubuntu-precise
For travis-ci/travis-ci#4516. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229074
> Pull request for xpdf

- ubuntu-precise
For travis-ci/apt-package-whitelist#196. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229294
> Pull request for libftdi1

- ubuntu-precise
For travis-ci/apt-package-whitelist#198. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229301
> Pull request for liblo-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#210. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229354
> Pull request for libstroke0-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#211. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229361
> Pull request for groff

- ubuntu-precise
For travis-ci/apt-package-whitelist#220. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229398
> Pull request for awesome

- ubuntu-precise
For travis-ci/apt-package-whitelist#195. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229290
> Pull request for libftdi-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#218. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229396
> Pull request for aria2

- ubuntu-precise
For travis-ci/travis-ci#4458.
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72207918
> Pull request for libsimage-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#69. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284655
> Pull request for python3-cairo-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#41. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284631
> Pull request for bisonc++

- ubuntu-precise
For travis-ci/apt-package-whitelist#39. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284611
> Pull request for python-mysqldb

- ubuntu-precise
For travis-ci/apt-package-whitelist#87. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284661
> Pull request for libgraph-easy-perl

- ubuntu-precise
For travis-ci/apt-package-whitelist#99. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284704
> Pull request for hunspell-en-us

- ubuntu-precise
For travis-ci/apt-package-whitelist#104. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284717
> Pull request for yum

- ubuntu-precise
For travis-ci/apt-package-whitelist#312. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72284982
> Pull request for python-ldap

- ubuntu-precise
For travis-ci/travis-ci#4513. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229067
> Pull request for indent

- ubuntu-precise
For travis-ci/travis-ci#4533. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229091
> Pull request for colormake

- ubuntu-precise
For travis-ci/travis-ci#4537. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72229103
> Pull request for libfaad2

- ubuntu-precise
For travis-ci/travis-ci#4420. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72228954
> Pull request for python-pil

- ubuntu-precise
For travis-ci/travis-ci#4479. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365248
> Pull request for libluajit-5.1-2

- ubuntu-precise
For travis-ci/travis-ci#4540. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365280
> Pull request for libstdc++-arm-none-eabi-newlib

- ubuntu-precise
For travis-ci/apt-package-whitelist#330. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365353
> Pull request for libxv-dev

- ubuntu-precise
For travis-ci/apt-package-whitelist#98. Ran tests and found no setuid bits. See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72365330
> Pull request for g++-4.8-multilib:i386

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#361.
Add packages: libkyotocabinet16 libkyotocabinet16-dbg kyotocabinet-utils kyotocabinet-doc libkyotocabinet-dev
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545294
> Pull request for libkyotocabinet16

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#373.
Add packages: libgstreamer1.0-0 libgstreamer1.0-0-dbg libgstreamer1.0-dev gstreamer1.0-doc gstreamer1.0-tools gir1.2-gstreamer-1.0
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545381
> Pull request for libgstreamer1.0-0

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#359.
Add packages: libc++1 libc++-dev libc++-test libc++abi1 libc++abi-dev libc++abi-test libc++-helpers
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545284
> Pull request for libc++1

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#366.
Add packages: libsdl2-2.0-0 libsdl2-dev libsdl2-dbg
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545328
> Pull request for libsdl2-2.0-0

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#400.
Add packages: cpp-arm-linux-gnueabihf g++-arm-linux-gnueabihf gobjc-arm-linux-gnueabihf gobjc++-arm-linux-gnueabihf gfortran-arm-linux-gnueabihf gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf
See https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545536
> Pull request for cpp-arm-linux-gnueabihf

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#420.
Add packages: python-openssl python-openssl-doc python3-openssl
See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545613.
> Pull request for python-openssl

- ubuntu-precise
Resolves travis-ci/apt-package-whitelist#425.
Add packages: libvips38 libvips-dev libvips-tools python-vipscc libvips-doc
See http://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72545621.
> Pull request for libvips38
